tasks:  
  - name: Build and preview help  
    init: |  
      cd cli  
      mvn clean package  
      java -jar ./target/benchmark-1.3.jar -h  
  - name: Start benchmark service  
    command: |  
      docker compose up results  
