services:

  bench:
   image: maven
   volumes: 
    - ./cli/target/benchmark-1.3.jar:/benchmark.jar
   command: java -jar /benchmark.jar --benchmark-target=mongo --target-database-host=mongo --target-database-port=27017 --target-database-user="" --target-database-password="" 
   deploy:
    restart_policy:
     condition: on-failure
     delay: 5s
     max_attempts: 3
   depends_on: 
    - mongo
    - postgres

  mongo:
    image: mongo
    expose:
      - "27017:27017"
    command:
     mongod --bind_ip_all --replSet rs0
    deploy:
      replicas: 3

  mongo-init-replica-set:
    image: mongo
    depends_on:
      mongo:
        condition: service_started
    entrypoint: |
      bash -xc '
        mongosh --host mongo --eval "
         rs.initiate( {_id: \"rs0\", members: [
          {_id: 0, priority: 3, host: \"${COMPOSE_PROJECT_NAME}-mongo-1:27017\"},
          {_id: 1, priority: 2, host: \"${COMPOSE_PROJECT_NAME}-mongo-2:27017\"},
          {_id: 2, priority: 1, host: \"${COMPOSE_PROJECT_NAME}-mongo-3:27017\"}
          ]
         });
        "
      '
      
# TODO: add two standbys to PostgreSQL

  postgres:
    image: postgres
    expose:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres

 