services:

  bench-mongo:
   build: .
   command: java -jar benchmark.jar --benchmark-target=mongo --target-database-host=${COMPOSE_PROJECT_NAME}-mongo-1 --target-database-name=test --target-database-password='' --target-database-port=27017 --target-database-user=''
   depends_on: 
    - mongo

  mongo:
    image: mongo
    expose:
      - "27017:20017"
    command:
     mongod --bind_ip_all --replSet rs0
    deploy:
      replicas: 3

  mongo-init-replica-set:
    image: mongo
    depends_on:
      mongo:
        condition: service_started
    entrypoint: |
      bash -xc '
        mongosh --host mongo --eval "
         rs.initiate( {_id: \"rs0\", members: [
          {_id: 0, priority: 3, host: \"${COMPOSE_PROJECT_NAME}-mongo-1:27017\"},
          {_id: 1, priority: 2, host: \"${COMPOSE_PROJECT_NAME}-mongo-2:27017\"},
          {_id: 2, priority: 1, host: \"${COMPOSE_PROJECT_NAME}-mongo-3:27017\"}]
         });
        "
      '
      